{
    "An exception of category 'FileReadError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Reading branch EventAuxiliary\n   [3] Calling XrdFile::readv()\n   [4] XrdAdaptor::ClientRequest::HandleResponse() failure while running connection recovery\n   [5] In XrdAdaptor::RequestManager::requestFailure()\nException Message:\nXrdAdaptor::RequestManager::requestFailure Open(name='root://eoscms//eos/cms/store/data/Run2012A/MinimumBias/RAW/v1/000/191/226/02F7EB61-0986-E111-A66F-5404A63886B4.root?svcClass=default', flags=0x10, permissions=0660, old source=p05614920j40522.cern.ch:1095 (unknown site)) => timeout when waiting for file open\n   Additional Info:\n      [a] Original error: '[ERROR] Operation expired' (errno=0, code=206, source=p05614920j40522.cern.ch:1095 (unknown site)).\n      [b] Disabled source: p05614920j40522.cern.ch:1095\n": [
        "1003.0"
    ],
    "An exception of category 'LogicError' occurred while\n   [0] Processing run: 1\n   [1] Calling global beginRun for module Pythia8HadronizerFilter/'generator'\nException Message:\n::getByToken: An attempt was made to read a Run product before endRun() was called.\nThe index of the token was 1.\n": [
        "516.0",
        "519.0",
        "525.0",
        "528.0",
        "513.0",
        "521.0",
        "523.0"
    ],
    "An exception of category 'OutputOpenError' occurred while\n   [0] Processing run: 1\n   [1] Calling global beginRun for module ExternalLHEProducer/'externalLHEProducer'\nException Message:\nUnable to open script output file cmsgrid_final.lhe (errno=2, No such file or directory).\n": [
        "522.0",
        "512.0",
        "515.0",
        "518.0",
        "529.0",
        "526.0"
    ]
}